name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # Увеличенный таймаут сборки (например, 3 часа)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yourdockerhubusername/yourimagename:latest
          build-args: |
            ROCMVERSION=6.3.3
            JETPACK5VERSION=r35.4.1
            JETPACK6VERSION=r36.4.0
            CMAKEVERSION=3.27.6
            GOVERSION=1.22.0
